### ISSUE TITLE
vue的总是报 plugins 应该为数组类型

### ISSUE THREAD

**Issue by huangzhaorongit** [NervJS/taro-components-sample#17]
Taro 配置有误，请检查！ (/Users/huangzhaorongit/Documents/lacesarworkspace/lacesarPos/taro-components-sample/config/index.js)
  [✗] plugins 应该为数组类型
找不到 vue-loader，请先安装。

**Comment by Chen-jj** [comment]
@huangzhaorongit 没有复现，更新后再试试 

![image](https://user-images.githubusercontent.com/11807297/140917919-3f23c780-1fa0-4889-b416-55328297f4a2.png)
