### ISSUE TITLE
组件继承中部分 methods 不可用

### ISSUE THREAD

**Issue by wq155** [NervJS/taro-components-sample#4]
VM54:1 Component "pages/component/index" does not have a method "kindToggle" to handle event "tap".

**Comment by luckyadam** [comment]
你的 taro 版本多少呢

**Comment by wq155** [comment]
> 你的 taro 版本多少呢
Taro v1.0.0-beta.30    
win 10 
node v8.1.2

**Comment by luckyadam** [comment]
cli 和 本地项目依赖都是 1.0.0-beta.30 么

**Comment by wq155** [comment]
> cli 和 本地项目依赖都是 1.0.0-beta.30 么

 [本地项目依赖都是package.json里的[https://github.com/NervJS/taro-components-sample/blob/master/package.json](url)

**Comment by luckyadam** [comment]
项目依赖也都升级到 1.0.0-beta.30 试试

**Comment by wq155** [comment]
> 项目依赖也都升级到 1.0.0-beta.30 试试

感谢大佬   可以了关闭了

**Comment by luckyadam** [comment]
OJBK
