### ISSUE TITLE
少了什么配置吗？我将WxParse引入项目之后，小程序端正常编译，但是H5端报错，报错图片如下：

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro-components-sample#5]
<img width="633" alt="2018-09-18 9 28 03" src="https://user-images.githubusercontent.com/29066081/45660450-6a86b100-bb2b-11e8-8b5b-83ab78e76cb1.png">
请大神看看。

**Comment by luckyadam** [comment]
在 Taro 的 issue 中已经答复~
