### ISSUE TITLE
首页点击无效

### ISSUE THREAD

**Issue by hecomzhangzhiguo** [NervJS/taro-components-sample#6]
点击报了如下警告。
Do not have kindToggle handler in current page: pages/component/index. Please make sure that kindToggle handler has been defined in pages/component/index, or pages/component/index has been added into app.json

**Comment by jinjinjin0731** [comment]
cli 和 本地项目依赖都是 1.0.0-beta.30 么

**Comment by hecomzhangzhiguo** [comment]
都是刚装的

**Comment by hecomzhangzhiguo** [comment]
昨天的不好使，更新完最新的依赖可以了，谢谢。
